### ISSUE TITLE
Disable lambda function versioning?

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/terraform-aws-cloudfront-lambda-directory-index#9]
@JonRoma unfortunately testing has shown that It is not possible to use $LATEST in variable cloudfront_lambda_origin_request_arn. Amazon, or Terraform, requires a specific version. I think we should consider dropping versioning, or better allow the end user to decide on what behavior he desires. For us I think we would prefer no version so we get automatic updates without having to reapply each distribution. But this is something that needs to be thought about and documented.

**Comment by ddriddle** [comment]
@JonRoma function versioning is required for CloudFront: https://advancedweb.hu/how-to-use-lambda-edge-with-terraform/.

Here is a direct quote from the AWS docs:

> You must specify the ARN of a function version; you can't specify a Lambda alias or $LATEST.
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_LambdaFunctionAssociation.html

**Comment by JonRoma** [comment]
@ddriddle, did we complete and document a workaround for this deficiency in the Amazon API? If so, this issue is redundant and can be closed. Otherwise, let's add a comment listing what still needs doing.

**Comment by ddriddle** [comment]
This has been addressed. Nothing left to do. 

In summary, versioning is required for lambda@edge functions, and we do need to remember for future work that we will always need to create an alias latest for all of our lambda@edge functions.
